// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace apidemo.Models
{
    public partial class Course : IValidatableObject
    {
        public Course()
        {
            CourseInstructor = new HashSet<CourseInstructor>();
            Enrollment = new HashSet<Enrollment>();
        }

        [Key]
        [Column("CourseID")]
        public int CourseId { get; set; }
        [Required(ErrorMessage ="請輸入課程名稱")]
        [StringLength(50, ErrorMessage = "課程名稱不可超過50字")]
        public string Title { get; set; }
        [Required]
        [Range(1,5,ErrorMessage = "Credits 不可超過5")]
        public int Credits { get; set; }
        [Column("DepartmentID")]
        public int DepartmentId { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Course")]
        public virtual Department Department { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseInstructor> CourseInstructor { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(Credits > 3 && !this.Title.Contains("優"))
            {
                yield return new ValidationResult("評價大於3個課程，請在課程名稱加入[優]字樣", new string[] { "Title" });
            }
        }
    }
}